artifact_location: /home/ubuntu/certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/284537927175947244
creation_time: 1701313199345
experiment_id: '284537927175947244'
last_update_time: 1701313199345
lifecycle_stage: active
name: test2
