artifact_location: /home/ubuntu/certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/151240189558065873
creation_time: 1701319598957
experiment_id: '151240189558065873'
last_update_time: 1701319598957
lifecycle_stage: active
name: test3
