artifact_location: /home/ubuntu/certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/470461454562751825
creation_time: 1701279673271
experiment_id: '470461454562751825'
last_update_time: 1701279673271
lifecycle_stage: active
name: test
