channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - numpy==1.24.4
  - pandas==2.0.3
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==2.0.0
name: mlflow-env
